### ISSUE TITLE
Cannot cast InputPeerChat to any kind of InputChannel

### ISSUE THREAD

**Issue by benborges** [estebanpdl/telegram-api#1]
OS : Ubuntu 21
Python : 3.10.4

- I'm using : python main.py --batch-file 'channels_text_file.txt' as source of channels, with one channel per line. 
- I'm able to see the JSON/CSV files getting created

After a successful installation of the requirements, I'm able to run it
![image](https://user-images.githubusercontent.com/10617712/169331258-e4fe221b-b45d-4e9a-b9c6-b6b08d412e58.png)

but after a while, a few minutes, it crashes with this error : 

`Traceback (most recent call last):
  File "/home/peer/tg-api/main.py", line 176, in <module>
    counter = write_collected_chats(
  File "/home/peer/tg-api/utils/__init__.py", line 142, in write_collected_chats
    ch['participants_count'] = process_participants_count(client, ch_id)
  File "/home/peer/tg-api/utils/__init__.py", line 73, in process_participants_count
    channel_request = loop.run_until_complete(
  File "/home/peer/.pyenv/versions/3.10.4/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/peer/tg-api/api/__init__.py", line 85, in full_channel_req
    return await client(
  File "/home/peer/.pyenv/versions/3.10.4/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/peer/.pyenv/versions/3.10.4/lib/python3.10/site-packages/telethon/client/users.py", line 39, in _call
    await r.resolve(self, utils)
  File "/home/peer/.pyenv/versions/3.10.4/lib/python3.10/site-packages/telethon/tl/functions/channels.py", line 720, in resolve
    self.channel = utils.get_input_channel(await client.get_input_entity(self.channel))
  File "/home/peer/.pyenv/versions/3.10.4/lib/python3.10/site-packages/telethon/utils.py", line 263, in get_input_channel
    _raise_cast_fail(entity, 'InputChannel')
  File "/home/peer/.pyenv/versions/3.10.4/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(

TypeError: Cannot cast InputPeerChat to any kind of InputChannel.`

I'm not a Python dev in itself so any hint to help me in the right direction to debug this would be very appreciated, 
I'm not 100% but this error could entirely be only on my end.

**Comment by estebanpdl** [comment]
Hi, @benborges. Thanks for sending this issue. Will check this out. It seems that one of the requests for one of the found channels failed. It seems your request is ok, the problem occurred when the program started getting data from channels associated with your request. Will try to update the repo with a new version

**Comment by estebanpdl** [comment]
Hi, @benborges. Could you provide the channel that generated the error? I tested the request with this one telehunt_watch, per your image, but it ran very well.

**Comment by benborges** [comment]
> 

I think the offending channel is t.me/video_posts or t.me/photo_posts



ps : I'm running it now to try to get this error again and make sure which channel is concerned
it might also be t.me/ukrainian_posts or t.me/ukrainian_videos

**Comment by estebanpdl** [comment]
I ran the program using those examples but I was not able to replicate the error. I updated the repo. Maybe you want to update the one you have locally.

**Comment by benborges** [comment]
Thanks a lot, I will and report back if it keeps happening
