### ISSUE TITLE
Pandas Merge Error

### ISSUE THREAD

**Issue by Firebug24k** [estebanpdl/telegram-api#13]
When running this on a large channel I get the following error:

> Writing channel data...
> done.

> Writing posts data...
> done.

Traceback (most recent call last):
  File "/empire/secure/telegram/newscript/telegram-tracker/main.py", line 387, in <module>
    df = df.merge(counter_df, how='left', on='id')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firebug/miniconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 10832, in merge
    return merge(
           ^^^^^^
  File "/home/firebug/miniconda3/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 184, in merge
    return op.get_result(copy=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firebug/miniconda3/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 888, in get_result
    result = self._reindex_and_concat(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firebug/miniconda3/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 840, in _reindex_and_concat
    llabels, rlabels = _items_overlap_with_suffix(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firebug/miniconda3/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 2757, in _items_overlap_with_suffix
    raise MergeError(
pandas.errors.MergeError: Passing 'suffixes' which cause duplicate columns {'from_messages_x', 'channel_req_targeted_by_x', 'channel_request_x', 'source_x', 'counter_x'} is not allowed.

**Comment by estebanpdl** [comment]
Could you let me know if you tried to add new information to an existing file? The current tool should not be creating duplicate columns.

**Comment by SmartFinn** [comment]
I'm facing with this issue too. Yes, this is happened when I tried to update an existing dataset. Here's the broken output folder [output.tar.gz](https://github.com/user-attachments/files/16608396/output.tar.gz), and the command used for update was:
`python3 main.py --telegram-channel WarArchive_ua`

**Comment by estebanpdl** [comment]
A virtual environment is recommended to avoid conflict in the versions of the libraries. Also, the tool is not designed to update existing databases. Use a different output path.

**Comment by estebanpdl** [comment]
In the coming weeks, I'll update the repository with new functionalities. These new functionalities may help to avoid these issues. Thanks all for your patience 🙏
