### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by dreuben79** [estebanpdl/telegram-api#14]
Saludos Esteban, tenés idea de si el script todavía funciona? Sigo recibiendo errores de Invalid Syntax con un request básico:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/codeop.py", line 161, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/codeop.py", line 73, in _maybe_compile
    return compiler(source, filename, symbol, incomplete_input=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/codeop.py", line 126, in __call__
    codeob = compile(source, filename, symbol, flags, True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<input>", line 1
    python main.py --telegram-channel londonantiulez
           ^^^^
SyntaxError: invalid syntax

Será que estoy haciendo algo mal?

**Comment by estebanpdl** [comment]
Hola, @dreuben79 
Estás añadiendo ese request dentro de un archivo .py o en línea de comando?

El request `python main.py --telegram-channel londonantiulez` debe ser ejecutado a través de la línea de comando o terminal.

**Comment by dreuben79** [comment]
Saludos, Esteban, gracias. Lo estoy tratando de correr en la consola de PyCharm.

Después de importar los módulos me da un error al importar el submódulo de la API de Telegram:

from api import *
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'api'

No sé si vendrá de ahí el problema... Ya tengo las credenciales en el config.ini e instalé todos los paquetes de requirements. Gracias de nuevo.

**Comment by estebanpdl** [comment]
Seguro sí. Nunca lo testeé en PyCharm. Te recomiendo lo realices de manera local, instalando los módulos en un ambiente de desarrollo nuevo, y ejecutando el request desde tu consola.

**Comment by dreuben79** [comment]
Gracias Esteban, efectivamente, desde la terminal no me dio el error.
