### ISSUE TITLE
Key error 'Telegram API credentials'

### ISSUE THREAD

**Issue by OscarR-A** [estebanpdl/telegram-api#6]
Hi 

I've set up the tool via gitclone and entered my credentials into the config file but I am receiving this error when I try to test run. Any advice on how to fix? I have entered my phone number in the required format and do not receive a text when running the script.

C:\Users\user\Desktop\Telegram api>python "C:\Users\user\Desktop\Telegram api\telegram-api\main.py" --telegram-channel omonmoscow
C:\Users\user\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Telegram api\telegram-api\main.py", line 71, in <module>
    config_attrs = get_config_attrs()
  File "C:\Users\user\Desktop\Telegram api\telegram-api\utils\__init__.py", line 33, in get_config_attrs
    attrs = config['Telegram API credentials']
  File "C:\Users\user\anaconda3\lib\configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'Telegram API credentials'

**Comment by OscarR-A** [comment]
I've updated NUMEXPR to remove the pandas warning

**Comment by OscarR-A** [comment]
Resolved I was running from a shell rather than from the cmd prompt
